version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./news_project:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-@fy*pvs5f9u-$@=ei(!f+8e(su+*a6a!=338=i(57oe9=r_&ca
    restart: on-failure
